name: Secrets test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Secret echo
      run: |
        $variable = "${{ secrets.SamsPassword }}"
        write-host "password raw: ${{ secrets.SamsPassword }}"
        write-host "password processed: $variable"
